version: '3.3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  mongo:
    container_name: nodejs-clean-architecture_mongo
    image: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
